name: Use Secret in HTTP request

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make request
        run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" \
               https://example.com/api/endpoint
